name: maze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/

      - name: Build
        run: npm run build
        working-directory: frontend/

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            frontend/dist

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #   - name: 'az login'
  #     uses: azure/login@v1
  #     with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #   - uses: actions/download-artifact@v3

  #   - name: Upload
  #     uses: azure/CLI@v1
  #     with:
  #       inlineScript: |
  #         az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} -d '$web' -s ./dist/ --overwrite
