import { CellProps } from "./Cell";
import { ItemCellMemoized } from "./ItemCell";
import { StartingCellMemoized } from "./StartingCell";

export const things = [
  "genie",
  "ring",
  "map",
  "ghost",
  "rat",
  "dragon",
  "troll",
  "candles",
  "chest",
  "crown",
  "book",
  "lizzard",
  "bat",
  "owl",
  "moth",
  "spider",
  "armor",
  "emerald",
  "keys",
  "moneysack",
  "elf",
  "scarab",
  "sword",
  "skull",
] as const;

export type Thing = (typeof things)[number];

/**
 * These are the fixes cells which cannot be moved
 */
export const fixedCells: readonly (CellProps | undefined)[] = [
  { type: "L", rotation: 90, content: <StartingCellMemoized color="green" /> },
  undefined,
  { type: "T", rotation: 180, content: <ItemCellMemoized item="genie" /> },
  undefined,
  { type: "T", rotation: 180, content: <ItemCellMemoized item="map" /> },
  undefined,
  { type: "L", rotation: 180, content: <StartingCellMemoized color="red" /> },
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  { type: "T", rotation: 90, content: <ItemCellMemoized item="candles" /> },
  undefined,
  { type: "T", rotation: 90, content: <ItemCellMemoized item="chest" /> },
  undefined,
  { type: "T", rotation: 180, content: <ItemCellMemoized item="crown" /> },
  undefined,
  { type: "T", rotation: 270, content: <ItemCellMemoized item="book" /> },
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  { type: "T", rotation: 90, content: <ItemCellMemoized item="armor" /> },
  undefined,
  { type: "T", rotation: 0, content: <ItemCellMemoized item="emerald" /> },
  undefined,
  { type: "T", rotation: 270, content: <ItemCellMemoized item="keys" /> },
  undefined,
  { type: "T", rotation: 270, content: <ItemCellMemoized item="moneysack" /> },
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  { type: "L", rotation: 0, content: <StartingCellMemoized color="blue" /> },
  undefined,
  { type: "T", rotation: 0, content: <ItemCellMemoized item="sword" /> },
  undefined,
  { type: "T", rotation: 0, content: <ItemCellMemoized item="skull" /> },
  undefined,
  { type: "L", rotation: 270, content: <StartingCellMemoized color="yellow" /> },
];

/**
 * All the other cells which can me moved and rotated
 * Note that one is left out for the player
 */
export const movableCells: readonly (Omit<CellProps, "rotation"> | undefined)[] = [
  { type: "T", content: <ItemCellMemoized item="ring" /> },
  { type: "T", content: <ItemCellMemoized item="ghost" /> },
  { type: "T", content: <ItemCellMemoized item="dragon" /> },
  { type: "T", content: <ItemCellMemoized item="bat" /> },
  { type: "T", content: <ItemCellMemoized item="elf" /> },
  { type: "T" },
  { type: "T" }, // hmm is this the correct one? count them...

  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },

  { type: "L", content: <ItemCellMemoized item="lizzard" /> },
  { type: "L", content: <ItemCellMemoized item="owl" /> },
  { type: "L", content: <ItemCellMemoized item="moth" /> },
  { type: "L", content: <ItemCellMemoized item="spider" /> },
  { type: "L", content: <ItemCellMemoized item="scarab" /> },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
];
