import { TileProps } from "./Tile";
import { ItemTileMemoized } from "./ItemTile";
import { StartingTileMemoized } from "./StartingTile";

export const things = [
  "genie",
  "ring",
  "map",
  "ghost",
  "rat",
  "dragon",
  "troll",
  "candles",
  "chest",
  "crown",
  "book",
  "lizzard",
  "bat",
  "owl",
  "moth",
  "spider",
  "armor",
  "emerald",
  "keys",
  "moneysack",
  "elf",
  "scarab",
  "sword",
  "skull",
] as const;

export type Thing = (typeof things)[number];

/**
 * These are the fixes tiles which cannot be moved
 */
export const fixedTiles: readonly (TileProps | undefined)[] = [
  { type: "L", rotation: 90, content: <StartingTileMemoized color="green" /> },
  undefined,
  { type: "T", rotation: 180, content: <ItemTileMemoized item="genie" /> },
  undefined,
  { type: "T", rotation: 180, content: <ItemTileMemoized item="map" /> },
  undefined,
  { type: "L", rotation: 180, content: <StartingTileMemoized color="red" /> },
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  { type: "T", rotation: 90, content: <ItemTileMemoized item="candles" /> },
  undefined,
  { type: "T", rotation: 90, content: <ItemTileMemoized item="chest" /> },
  undefined,
  { type: "T", rotation: 180, content: <ItemTileMemoized item="crown" /> },
  undefined,
  { type: "T", rotation: 270, content: <ItemTileMemoized item="book" /> },
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  { type: "T", rotation: 90, content: <ItemTileMemoized item="armor" /> },
  undefined,
  { type: "T", rotation: 0, content: <ItemTileMemoized item="emerald" /> },
  undefined,
  { type: "T", rotation: 270, content: <ItemTileMemoized item="keys" /> },
  undefined,
  { type: "T", rotation: 270, content: <ItemTileMemoized item="moneysack" /> },
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  { type: "L", rotation: 0, content: <StartingTileMemoized color="blue" /> },
  undefined,
  { type: "T", rotation: 0, content: <ItemTileMemoized item="sword" /> },
  undefined,
  { type: "T", rotation: 0, content: <ItemTileMemoized item="skull" /> },
  undefined,
  { type: "L", rotation: 270, content: <StartingTileMemoized color="yellow" /> },
];

/**
 * All the other tiles which can me moved and rotated
 * Note that one is left out for the player
 */
export const movableTiles: readonly (Omit<TileProps, "rotation"> | undefined)[] = [
  { type: "T", content: <ItemTileMemoized item="ring" /> },
  { type: "T", content: <ItemTileMemoized item="ghost" /> },
  { type: "T", content: <ItemTileMemoized item="dragon" /> },
  { type: "T", content: <ItemTileMemoized item="bat" /> },
  { type: "T", content: <ItemTileMemoized item="elf" /> },
  { type: "T" },
  { type: "T" }, // hmm is this the correct one? count them...

  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },
  { type: "I" },

  { type: "L", content: <ItemTileMemoized item="lizzard" /> },
  { type: "L", content: <ItemTileMemoized item="owl" /> },
  { type: "L", content: <ItemTileMemoized item="moth" /> },
  { type: "L", content: <ItemTileMemoized item="spider" /> },
  { type: "L", content: <ItemTileMemoized item="scarab" /> },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
  { type: "L" },
];
